- name: LOGO_THUMBNAIL
  value: '/brand-assets/logo_thumbnail.svg'
- name: LOGO
  value: '/brand-assets/logo.svg'
- name: INSTALLATION_NAME
  value: 'WevrLabs Communication Center'
- name: BRAND_URL
  value: 'https://wevrlabs.net'
- name: WIDGET_BRAND_URL
  value: 'https://wevrlabs.net'
- name: TERMS_URL
  value: 'https://wevrlabs.net/tos'
- name: PRIVACY_URL
  value: 'https://wevrlabs.net/tos'
- name: DISPLAY_MANIFEST
  value: true
- name: MAILER_INBOUND_EMAIL_DOMAIN
  value: 'sandboxa54b342eefc74ea497ae292bdb78ca21.mailgun.org'
- name: MAILER_SUPPORT_EMAIL
  value: 'care@wevrlabs.net'
- name: CREATE_NEW_ACCOUNT_FROM_DASHBOARD
  value: false
- name: BRAND_NAME
  value: 'WevrLabs Communication Center'
- name: 'INSTALLATION_EVENTS_WEBHOOK_URL'
  value: 